### ISSUE TITLE
Don't load dashboard on login page

### ISSUE THREAD

**Issue by thompol** [firecups/ispconfig-firecups-theme#6]
See https://git.ispconfig.org/ispconfig/ispconfig3/-/commit/36393c2b60cd65e1a033dc498d3eb96b480166ea

Seems like the current files are based on 3.1.15p3 and not 3.2, so there might be more things missing. Just sharing them with you :)

**Comment by firecups** [comment]
interesting. i use the files from the v3.2, but i will check this....
But the login page is the orgin default theme.

**Comment by thompol** [comment]
Yes, so it's not needed unless you configure a different theme for the login page 👍 

I think I opened issues for every thing that was missing, but make sure to keep an eye on the ISPConfig repo.

**Comment by firecups** [comment]
Thanks a lot for your big feedbacks ;-) That´s a big help.

**Comment by thompol** [comment]
No problem, let me know either here or through a forum PM if you need anything.
